# Generated by Django 5.1 on 2024-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
