# Generated by Django 5.1 on 2024-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_chatmessage_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_comment', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('advice', models.TextField()),
            ],
        ),
    ]
