image: docker:latest  # Docker가 포함된 기본 이미지

services:
  - docker:dind  # Docker-in-Docker 서비스 활성화

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

# Docker 이미지를 빌드하고 푸시
build:
  stage: build
  script:
    - docker version  # Docker가 제대로 설치되었는지 확인
    - docker build -t skn4card/test_final:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push skn4card/test_final:latest

# Lightsail 서버에 배포
deploy:
  stage: deploy
  only:
    - main  # main 브랜치에서만 실행
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$django_key" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.39.220.210 "
        if [ ! -d /home/ubuntu/cicd_docker/.git ]; then
          git clone https://oauth2:$GITLAB_TOKEN@gitlab.com/skn_finalproject/skn_final_project_django.git /home/ubuntu/cicd_docker;
        else
          cd /home/ubuntu/cicd_docker && git reset --hard && git pull https://oauth2:$GITLAB_TOKEN@gitlab.com/skn_finalproject/skn_final_project_django.git;
        fi &&
        cd /home/ubuntu/cicd_docker &&
        docker pull skn4card/test_final:latest &&
        docker-compose down &&
        docker-compose up -d
      "


