
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:  # .env 파일 연결
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles  # 정적 파일 공유
      - /etc/letsencrypt:/etc/letsencrypt  # Let's Encrypt 인증서 경로만 마운트
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 추가
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:

volumes:
  static_volume:
  media_volume:
